// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI needs a URL to run migrations against. Fail loudly here rather
    // than letting Prisma report a confusing "no datasource" error later.
    url: process.env["DATABASE_URL"] ?? "",
  },
});
