import { hash as argonHash, verify as argonVerify } from "@node-rs/argon2";
import type { Algorithm } from "@node-rs/argon2";
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * Passwords and API keys are both secrets, but they are hashed with different
 * algorithms on purpose. The reasoning is worth spelling out, because using
 * the same approach for both would be wrong in one direction or the other.
 *
 *   Passwords are chosen by humans, so they carry very little entropy —
 *   "hunter2" is one guess out of a few million, not out of 2^256. The only
 *   defence is to make each individual guess expensive, which is what Argon2
 *   is for: it deliberately burns CPU and memory per hash. Slow is the point.
 *
 *   API keys are generated by us from 32 bytes of cryptographic randomness.
 *   There is nothing to guess — brute-forcing 2^256 is not a thing an attacker
 *   does. Slow hashing buys no security here, and costs a great deal: it would
 *   run on every single event published, on the hottest path in the system.
 *
 * There is also a structural reason. Argon2 salts every hash randomly, so the
 * same key hashes differently each time. You cannot look a key up by its hash;
 * you would have to load every key in the database and verify one by one.
 * SHA-256 is deterministic, so the hash goes straight into a unique index and
 * the lookup is a single indexed query.
 */

// ─── Passwords ──────────────────────────────────────────────────────────────

/**
 * Argon2id — the variant recommended by OWASP. It blends Argon2i's resistance
 * to side-channel attacks with Argon2d's resistance to GPU cracking.
 *
 * These cost parameters follow the OWASP minimum. Raising memoryCost is the
 * most effective lever against attackers using GPUs, because memory is the
 * resource that parallelises worst for them.
 */
/**
 * `Algorithm.Argon2id` from @node-rs/argon2. The library declares that as a
 * TypeScript `const enum`, which cannot be imported as a value while
 * `verbatimModuleSyntax` is on, so the value is written out here rather than
 * left implicit. It is also the library's default; naming it explicitly means
 * a future change to that default cannot silently weaken our hashing.
 */
const ARGON2ID = 2 as Algorithm;

const ARGON_OPTIONS = {
  algorithm: ARGON2ID,
  memoryCost: 19_456, // 19 MiB
  timeCost: 2,
  parallelism: 1,
} as const;

export async function hashPassword(password: string): Promise<string> {
  return argonHash(password, ARGON_OPTIONS);
}

/**
 * Verify a password against its stored hash.
 *
 * Returns false rather than throwing on a malformed hash — a corrupt row
 * should read as "wrong password", not crash the login endpoint.
 */
export async function verifyPassword(
  storedHash: string,
  candidate: string,
): Promise<boolean> {
  try {
    return await argonVerify(storedHash, candidate);
  } catch {
    return false;
  }
}

// ─── API keys ───────────────────────────────────────────────────────────────

/**
 * Identifies these strings as Relay keys wherever they turn up. Secret
 * scanners (GitHub's included) match on prefixes like this, so a key
 * accidentally committed to a public repo can be detected and revoked.
 */
const API_KEY_PREFIX = "rlk_live_";

/** How much of the key is stored in clear for display in a key list. */
const DISPLAY_PREFIX_LENGTH = API_KEY_PREFIX.length + 6;

export interface GeneratedApiKey {
  /** The full key. Returned to the user exactly once and never stored. */
  plaintext: string;
  /** SHA-256 of the full key. This is what goes in the database. */
  hashed: string;
  /** Leading characters, safe to display: "rlk_live_a1b2c3". */
  prefix: string;
}

/**
 * Mint a new API key.
 *
 * 32 bytes of randomness from the OS CSPRNG — 256 bits of entropy, which is
 * not guessable by any means available now or later.
 */
export function generateApiKey(): GeneratedApiKey {
  const plaintext = API_KEY_PREFIX + randomBytes(32).toString("base64url");

  return {
    plaintext,
    hashed: hashApiKey(plaintext),
    prefix: plaintext.slice(0, DISPLAY_PREFIX_LENGTH),
  };
}

/**
 * Deterministic hash, so an incoming key can be looked up directly by its
 * hash through a unique index rather than compared against every stored key.
 */
export function hashApiKey(plaintext: string): string {
  return createHash("sha256").update(plaintext).digest("hex");
}

export function isApiKeyFormat(value: string): boolean {
  return value.startsWith(API_KEY_PREFIX);
}

// ─── Constant-time comparison ───────────────────────────────────────────────

/**
 * Compare two secrets without leaking their contents through timing.
 *
 * A plain `a === b` returns as soon as it hits a differing byte, so a wrong
 * value that shares a longer prefix takes measurably longer to reject. Given
 * enough samples an attacker can recover a secret one byte at a time. This
 * always reads both values in full.
 *
 * Used for webhook signature verification in M4, where the comparison is
 * against a value the caller controls.
 */
export function secureCompare(a: string, b: string): boolean {
  const bufferA = Buffer.from(a, "utf8");
  const bufferB = Buffer.from(b, "utf8");

  // timingSafeEqual throws on length mismatch, and the lengths themselves
  // aren't secret, so this early return leaks nothing worth having.
  if (bufferA.length !== bufferB.length) return false;

  return timingSafeEqual(bufferA, bufferB);
}
